spring.config.import=optional:file:.env[.properties]

spring.application.name=flower-api
server.port=8080

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
